---
- hosts: localhost
  tasks:
    - name: Update apt-get catalog
      apt:
        update_cache: true
      ignore_errors: True
    - name: Install nginx to latest version
      apt:
        name: nginx
        state: latest
    - name: Start nginx
      service:
        name: nginx
        state: started

