---
- hosts: localhost
  tasks:
    - name: Install nginx to latest version
      apt:
        name: nginx
        state: latest
    - name: Start nginx
      service:
        name: nginx
        state: started
